#!/bin/bash
# grant all privileges on *.* to 'django'@'%'identified by '123.com' with grant option;

number=$(yum list | awk '$1=="python36.x86_64" || $1=="python34.x86_64" {print $1}' | wc -l)

if [[ "$number" != "0" ]]; then
	if [[ "$number" > "0" ]]; then
		yum install $(yum list | awk '$1=="python36.x86_64" || $1=="python34.x86_64" {print $1}')
	else
		echo "请安装epel源"
		exit 0
	fi
fi

wget https://bootstrap.pypa.io/get-pip.py
wget http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz

number=$(ls /bin/ | awk '$1=="python3.4" || $1=="python3.6" {print $1}' | wc -l)
if [[ "$number" > "1" ]]; then
	pips="pip3.6"
	pythons="python3.6"
	
fi

tar zxvf setuptools-0.6c11.tar.gz
cd setuptools-0.6c11
$pythons setup.py build
$pythons setup.py install
cd ../
$pythons setup.py install

$pythons get-pip.py
$pips install Django
$pips install uwsgi