# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-28 07:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('time_add', models.DateTimeField()),
                ('time_now', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_now'],
                'permissions': (('app_see_article', '访问视图权限'), ('app_create_article', '创建留言权限'), ('app_edit_article', '编辑留言权限'), ('app_delete_article', '删除留言权限'), ('app_reply_discussion', '评论留言权限')),
            },
        ),
    ]
