# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app_blog',
            options={'ordering': ['-time_now'], 'permissions': (('app_see_article', '访问视图权限'), ('app_create_article', '创建留言权限'), ('app_edit_article', '编辑留言权限'), ('app_delete_article', '删除留言权限'), ('app_reply_discussion', '评论留言权限'))},
        ),
    ]
