# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180225_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_blog',
            name='time_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
